make: 
	@gcc A.c -o A
	@gcc B.c -o B
	@gcc testfile.c -o testfile
	@gcc initialise.c -o initialise
	@gcc finaltimestamp.c -o finaltimestamp
	@gcc initialtimestamp.c -o initialtimestamp
	@gcc computetime.c -o computetime
	@./initialise
	@./initialtimestamp
	@./testfile
	@./testfile
	@./testfile
	@./testfile
	@./testfile
	@./testfile
	@./testfile
	@./testfile
	@./testfile
	@./testfile
	@./finaltimestamp
	@./computetime
	


