make: 
	@gcc initialise.c -o initialise
	@gcc p1.c -o p1
	@gcc p2.c -o p2
	@gcc finaltimestamp.c -o finaltimestamp
	@gcc initialtimestamp.c -o initialtimestamp
	@gcc computetime.c -o computetime
	@clear
	@./initialtimestamp
	@./initialise
	@./finaltimestamp
	@./computetime

	
